### PR TITLE
Added helm chart

### PR DESCRIPTION
**Pull request by holmesb**
Resolves issue #31
Note that while the chart is in this PR, the helm repo is my branch for the time being. This git repo would need to be changed (https://helm.sh/docs/topics/chart_repository/) for it to be used as a helm repo.

By default it will be deployed on masters as well as workers (see tolarations in values.yaml).

**- Added helm chart**

### CODE REVIEW

**Comment by amimof** [comment]
Just came back from vacation so sorry for the late response. Thanks for the PR and nice work 👏 
Before I merge, may I also suggest a Helm section in the main README file?

**Comment by holmesb** [comment]
Done @amimof

**Comment by amimof** [comment]
I just noticed that the helm repo URL is pointing to your branch. I suggest we have that moved to this repo and move the `charts` directory to top level if required.

**Comment by holmesb** [comment]
I can't create a helm repo here, it's up to you: https://helm.sh/docs/topics/chart_repository/

**Comment by amimof** [comment]
Sorry, I get it now. I'll make sure to create a repo

**Comment by amimof** [comment]
@holmesb I took the liberty of making some modifications so that I can continue to create the Chart repo as part of the projects GH-pages. See 1b825c488c92a49810786a2c0ae5ef52a238e86a.

**Comment by holmesb** [comment]
Fine by me @aminof.  I'm an old Python guy so have a fetish for underscores ;-)

**Pull request merged**
