### PR TITLE
Allow excluding filenames, not just directories

### PR DESCRIPTION
**Pull request by DeX77**
The proposed change allows to also include filenames from path' of considered certs. This allows to do something like this:

--path=/etc/letsencrypt/live/ --exclude-path=privkey.pem

**- Description for the CHANGELOG**
*  Allow to also include filenames from path

### CODE REVIEW

**Comment by amimof** [comment]
Thanks for contributing 🎉 
Can you please add a simple test case that tests this new feature. Thanks

**Comment by rgl** [comment]
Maybe its out-of-scope of this PR, but, wouldn't it be better to use an inclusion mechanism instead? Like `-include-cert-glob C:\tmp\*-crt.pem` (as provided by https://github.com/joe-elliott/cert-exporter)

**Comment by amimof** [comment]
@rgl Yes I agree, might be a better pattern actually 🤔

**Comment by amimof** [comment]
I decided to open a PR which adds two new flags. `--include-glob` and `--exclude-glob` which addresses this. You can have a look at it and please let me know what you think. #51

**Comment by amimof** [comment]
#51 just merged which adds `--include-glop` and `--exclude-glob`. Closing this PR. Thanks for your help and input. Appreciate it!

**Pull request closed without merging**
