### PR TITLE
Added exclude-path parameter for excluding certain paths from scraping

### PR DESCRIPTION
**Pull request by folijosvanagas**
This enables user to define certain files or folders which will be escaped within a path what is scraped.

### CODE REVIEW

**Comment by amimof** [comment]
@folijosvanagas After the merge I tested the `--exclude-path` locally and it doesn’t seem to work. However changing the [following line](https://github.com/amimof/node-cert-exporter/commit/d05ff5bb7043dc77d94890b0711a3dcf7beb5cf8#diff-45e8ac85b2787e54fb11b0fc594625fbR26) to `return nil` instead of `continue` got it working. Do you agree?

**Comment by folijosvanagas** [comment]
Strange. The idea was to skip paths/files when doing `filepath.Walk` which matched exclude-paths. Continue should do just that.
Can you show with which flags have you performed the test so I could replicate it?

**Comment by amimof** [comment]
I pass two folders to `--path` and exlude one of them.
```
go run cmd/node-cert-exporter/main.go --logtostderr  --v=4 --path /etc/ssl,/Users/amir/Desktop/stuff --exclude-path=/Users/amir/Desktop/stuff
```

**Comment by amimof** [comment]
Doesn't `continue` "skip" to next iteration in the loop? But when the loop finishes it'll append the path to the `paths` variable further down.

**Comment by folijosvanagas** [comment]
Agh, yes! It's a `walk` function and not a simple loop. You are right - `return nil` will do it.

**Comment by amimof** [comment]
Cool, then I'll open a PR and get it fixed

**Pull request merged**
